name: Continuous Integration

on:
  pull_request:
    branches: ['main']

env:
  FLASK_APP: sde_prototype_govuk
  ENV: ci
  STATIC: sde_prototype_govuk/static

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version-file: '.python-version'
        cache: pip

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: 'package.json'
        cache: npm

    - name: Install dependencies
      run: |
        make install

    - name: Compile assets
      env:
        GOVUK_FRONTEND_VERSION: 4.3.1
        GOVUK_PUBLISHING_COMPONENTS_VERSION: 30.6.1
      run: |
        make assets

    - name: Test
      run: |
        make test-coverage
